# Generated by Django 4.2.7 on 2024-01-13 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosteler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='student1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='student1', to='hosteler.user_student'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='student2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='student2', to='hosteler.user_student'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='student3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='student3', to='hosteler.user_student'),
        ),
    ]
