# Generated by Django 4.2.7 on 2024-01-19 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosteler', '0003_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosteler.vacancy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosteler.user_student')),
            ],
        ),
    ]
