# Generated by Django 4.2.7 on 2024-01-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosteler', '0004_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='vacant',
            field=models.BooleanField(default=True),
        ),
    ]
